// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Q-hgwGmD_qmf3cd60X_ATvyqghXBMTg',
    appId: '1:987963468381:web:0f6e1e134d90285e687bb4',
    messagingSenderId: '987963468381',
    projectId: 'proyecto-arp-flutter',
    authDomain: 'proyecto-arp-flutter.firebaseapp.com',
    storageBucket: 'proyecto-arp-flutter.firebasestorage.app',
    measurementId: 'G-DTNDJYD4QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLCXb9-BoMyht63uuwZImmvp01amdc4CI',
    appId: '1:987963468381:android:1f4d217cab5690b2687bb4',
    messagingSenderId: '987963468381',
    projectId: 'proyecto-arp-flutter',
    storageBucket: 'proyecto-arp-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS4ex8VE-cGlnfP5pHClUsz1f7IXuc4z4',
    appId: '1:987963468381:ios:4ca2e2694b89c7f9687bb4',
    messagingSenderId: '987963468381',
    projectId: 'proyecto-arp-flutter',
    storageBucket: 'proyecto-arp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyecto2dam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS4ex8VE-cGlnfP5pHClUsz1f7IXuc4z4',
    appId: '1:987963468381:ios:4ca2e2694b89c7f9687bb4',
    messagingSenderId: '987963468381',
    projectId: 'proyecto-arp-flutter',
    storageBucket: 'proyecto-arp-flutter.firebasestorage.app',
    iosBundleId: 'com.example.proyecto2dam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Q-hgwGmD_qmf3cd60X_ATvyqghXBMTg',
    appId: '1:987963468381:web:5053baf1c2a78be6687bb4',
    messagingSenderId: '987963468381',
    projectId: 'proyecto-arp-flutter',
    authDomain: 'proyecto-arp-flutter.firebaseapp.com',
    storageBucket: 'proyecto-arp-flutter.firebasestorage.app',
    measurementId: 'G-L0PVY3VWWY',
  );
}
